# Mudar a tecla de prefixo de C-b para C-a
# C-a é mais fácil de alcançar e é o padrão do 'screen'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Habilitar o modo mouse
# Permite redimensionar painéis, selecionar janelas e rolar com o mouse
set -g mouse on

# Começar a numeração de janelas e painéis em 1, em vez de 0
set -g base-index 1
setw -g pane-base-index 1

# Dividir painéis com | e - (mais intuitivo)
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Navegação entre painéis no estilo Vim
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Mudar o tempo de espera de comandos para não haver delay
set -s escape-time 0

# Aumentar o histórico de scroll
set -g history-limit 10000

# Lista de plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator' # Plugin de integração que já tínhamos

# ADICIONE ESTA LINHA PARA O TEMA NORD
set -g @plugin 'nordtheme/tmux'



# Inicializa o TPM (deve ser a última linha do arquivo)
run '~/.tmux/plugins/tpm/tpm''
