[Appearance]
color_scheme_path=~/.config/qt6ct/colors/stratus.conf
custom_palette=true
icon_theme=Tela-circle-nord-dark
standard_dialogs=default
style=Fusion

[Fonts]
fixed="VictorMono Nerd Font,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
general="Geist,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"

[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x2\x86\0\0\0\x34\0\0\x4\xfa\0\0\x4\xa3\0\0\x2\x88\0\0\0\x36\0\0\x4\xf8\0\0\x4\xa1\0\0\0\x1\0\0\0\0\a\x80\0\0\x2\x88\0\0\0\x36\0\0\x4\xf8\0\0\x4\xa1)
